import type { ModuleManifest } from '../../types/modules';

export const mixerManifest: ModuleManifest = {
  type: 'mixer',
  label: 'Mixer',
  category: 'routing',
  soloSafe: true,
  ports: [
    {
      id: 'in1',
      label: 'In 1',
      direction: 'input',
      signalType: 'audio',
      channelFormat: 'stereo',
    },
    {
      id: 'in2',
      label: 'In 2',
      direction: 'input',
      signalType: 'audio',
      channelFormat: 'stereo',
    },
    {
      id: 'in3',
      label: 'In 3',
      direction: 'input',
      signalType: 'audio',
      channelFormat: 'stereo',
    },
    {
      id: 'in4',
      label: 'In 4',
      direction: 'input',
      signalType: 'audio',
      channelFormat: 'stereo',
    },
    {
      id: 'out',
      label: 'Output',
      direction: 'output',
      signalType: 'audio',
      channelFormat: 'stereo',
    },
  ],
  parameters: [
    {
      id: 'gain1',
      label: 'In 1',
      min: -70,
      max: 12,
      defaultValue: 0,
      step: 0.1,
      unit: 'dB',
      mapping: 'linear',
    },
    {
      id: 'gain2',
      label: 'In 2',
      min: -70,
      max: 12,
      defaultValue: 0,
      step: 0.1,
      unit: 'dB',
      mapping: 'linear',
    },
    {
      id: 'gain3',
      label: 'In 3',
      min: -70,
      max: 12,
      defaultValue: 0,
      step: 0.1,
      unit: 'dB',
      mapping: 'linear',
    },
    {
      id: 'gain4',
      label: 'In 4',
      min: -70,
      max: 12,
      defaultValue: 0,
      step: 0.1,
      unit: 'dB',
      mapping: 'linear',
    },
  ],
};
