import type { ModuleManifest } from '../../types/modules';

export const gateManifest: ModuleManifest = {
  type: 'gate',
  label: 'Gate',
  category: 'effect',
  ports: [
    {
      id: 'in',
      label: 'Audio In',
      direction: 'input',
      signalType: 'audio',
      channelFormat: 'stereo',
    },
    {
      id: 'sidechain',
      label: 'Sidechain',
      direction: 'input',
      signalType: 'audio',
      channelFormat: 'stereo',
    },
    {
      id: 'out',
      label: 'Output',
      direction: 'output',
      signalType: 'audio',
      channelFormat: 'stereo',
    },
  ],
  parameters: [
    {
      id: 'threshold',
      label: 'Threshold',
      min: -80,
      max: -10,
      defaultValue: -40,
      step: 0.5,
      unit: 'dB',
      mapping: 'linear',
    },
    {
      id: 'attack',
      label: 'Attack',
      min: 0.0001,
      max: 0.05,
      defaultValue: 0.001,
      step: 0.0001,
      unit: 's',
      mapping: 'log',
    },
    {
      id: 'hold',
      label: 'Hold',
      min: 0,
      max: 0.5,
      defaultValue: 0.05,
      step: 0.001,
      unit: 's',
      mapping: 'linear',
    },
    {
      id: 'release',
      label: 'Release',
      min: 0.01,
      max: 0.5,
      defaultValue: 0.1,
      step: 0.01,
      unit: 's',
      mapping: 'log',
    },
    {
      id: 'range',
      label: 'Range',
      min: -80,
      max: 0,
      defaultValue: -80,
      step: 0.5,
      unit: 'dB',
      mapping: 'linear',
    },
  ],
};
