import type { ModuleManifest } from '../../types/modules';

export const eqManifest: ModuleManifest = {
  type: 'eq',
  label: 'EQ',
  category: 'effect',
  ports: [
    {
      id: 'in',
      label: 'Input',
      direction: 'input',
      signalType: 'audio',
      channelFormat: 'stereo',
    },
    {
      id: 'out',
      label: 'Output',
      direction: 'output',
      signalType: 'audio',
      channelFormat: 'stereo',
    },
  ],
  parameters: [
    {
      id: 'lowFreq',
      label: 'Low Freq',
      min: 20,
      max: 500,
      defaultValue: 80,
      step: 1,
      unit: 'Hz',
      mapping: 'log',
    },
    {
      id: 'lowGain',
      label: 'Low Gain',
      min: -24,
      max: 24,
      defaultValue: 0,
      step: 0.5,
      unit: 'dB',
      mapping: 'linear',
    },
    {
      id: 'midFreq',
      label: 'Mid Freq',
      min: 200,
      max: 5000,
      defaultValue: 1000,
      step: 1,
      unit: 'Hz',
      mapping: 'log',
    },
    {
      id: 'midGain',
      label: 'Mid Gain',
      min: -24,
      max: 24,
      defaultValue: 0,
      step: 0.5,
      unit: 'dB',
      mapping: 'linear',
    },
    {
      id: 'midQ',
      label: 'Mid Q',
      min: 0.1,
      max: 18,
      defaultValue: 1,
      step: 0.1,
      unit: '',
      mapping: 'log',
    },
    {
      id: 'highFreq',
      label: 'High Freq',
      min: 2000,
      max: 20000,
      defaultValue: 8000,
      step: 1,
      unit: 'Hz',
      mapping: 'log',
    },
    {
      id: 'highGain',
      label: 'High Gain',
      min: -24,
      max: 24,
      defaultValue: 0,
      step: 0.5,
      unit: 'dB',
      mapping: 'linear',
    },
  ],
};
